### ISSUE TITLE
Is it up to date? Getting bad error when adding the transporter

### ISSUE THREAD

**Issue by bendpx** [RiptideCloud/winston-logentries-transport#3]
var util = require('util'),
    winston = require('winston'),
    Logentries = require('winston-logentries-transport').Logentries;

winston.add(new Logentries({ token: 'TOKEN' }));

Getting this error:
/node_modules/winston/lib/winston/logger.js:440
  var instance = created ? transport : (new (transport)(options));
                                        ^
TypeError: object is not a function
    at Logger.add (/node_modules/winston/lib/winston/logger.js:440:41)
    at Object.winston.(anonymous function) [as add] (/node_modules/winston/lib/winston.js:87:34)
    at Object.<anonymous> (/server/utils/logger.js:44:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/app.js:17:1)

**Comment by DavidTPate** [comment]
Hi there!

The module is still up-to-date and working, it looks like your code is just incorrect on where you are adding the transport to Winston.

Here's the correct syntax:
```js
var winston = require('winston');
var Logentries = require('winston-logentries-transport').Logentries;

winston.add(Logentries, { token: 'YOUR TOKEN HERE' });
```

If you compare this to the code that you provided you'll notice that you are adding an already created transport to Winston via: `winston.add(new Logentries({ token: 'TOKEN' }));`

**Comment by markstos** [comment]
This issues appears that it can be closed now.

**Comment by DavidTPate** [comment]
Yeah, I'm thinking so. Please re-open if you are still hitting issues @bendpx
